# Generated by Django 4.0.3 on 2022-04-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_appusermodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose', models.CharField(max_length=120)),
                ('physical_signature', models.CharField(max_length=120)),
                ('condition', models.TextField()),
                ('drugs', models.CharField(max_length=120)),
                ('next_appointment_date', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctorsmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientmodel')),
            ],
        ),
    ]
