# Generated by Django 4.0.3 on 2022-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_log_app', '0002_rename_date_visitationmodel_date_of_visitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitationmodel',
            name='drugs',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='visitationmodel',
            name='next_appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
