# Generated by Django 4.0.3 on 2022-04-13 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_appusermodel_role'),
        ('doc_log_app', '0004_alter_visitationmodel_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorsmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patientmodel')),
            ],
        ),
    ]
