# Generated by Django 4.0.3 on 2022-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_doctorsmodel_id_doctorsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='work_time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='work_time_to',
            field=models.TimeField(),
        ),
    ]
