# Generated by Django 4.0.3 on 2022-04-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patientmodel_id_alter_patientmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
