# Generated by Django 4.0.3 on 2022-04-03 10:00

import django.core.validators
from django.db import migrations, models
import doc_log.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patientmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='egn',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), doc_log.common.validators.only_digit_validator]),
        ),
    ]
