# Generated by Django 4.0.3 on 2022-04-03 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='doctorsmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
