# Generated by Django 4.0.3 on 2022-04-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_doctorsmodel_work_time_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialisationmodel'),
        ),
    ]
