# Generated by Django 4.0.3 on 2022-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_specialisationmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='specialisation',
            field=models.CharField(choices=[('Pediatrician', 'Pediatrician'), ('Neurologist', 'Neurologist'), ('Dermatologist', 'Dermatologist'), ('Surgeon', 'Surgeon'), ('Virologist', 'Virologist'), ('Cardiologist', 'Cardiologist'), ('ENT', 'ENT'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Dentist', 'Dentist')], max_length=13),
        ),
        migrations.DeleteModel(
            name='SpecialisationModel',
        ),
    ]
