# Generated by Django 4.0.3 on 2022-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_specialisationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor'), (2, 'Patient')], default=1),
            preserve_default=False,
        ),
    ]
