# Generated by Django 4.0.3 on 2022-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_doctorsmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='biography',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='education',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='allergens',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='operations',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='vaccines',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
