# Generated by Django 4.0.3 on 2022-04-16 16:14

from django.db import migrations, models
import doc_log.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_doctorsmodel_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profile_pics', validators=[doc_log.common.validators.image_size_validator_in_mb]),
        ),
    ]
