# Generated by Django 4.0.4 on 2022-04-28 09:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_doctorsmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Doctor'), (2, 'Patient')], default=3),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='specialisation',
            field=models.CharField(choices=[('1', 'Pediatrician'), ('2', 'Neurologist'), ('3', 'Dermatologist'), ('4', 'Surgeon'), ('5', 'Virologist'), ('6', 'Cardiologist'), ('7', 'ENT'), ('8', 'Gynecologist'), ('9', 'Urologist'), ('10', 'Dentist')], max_length=20),
        ),
        migrations.DeleteModel(
            name='SpecialisationModel',
        ),
    ]
