# Generated by Django 4.0.3 on 2022-04-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_log_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitationmodel',
            old_name='date',
            new_name='date_of_visitation',
        ),
    ]
